# Generated by Django 5.1.15 on 2026-04-15 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_sem_comunicacao_pausar', models.PositiveIntegerField(default=60, help_text='Usinas sem snapshot há mais deste número de dias são automaticamente desativadas (ativo=False) no início do próximo ciclo de coleta. Para retomar, reative manualmente no admin.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Dias sem comunicação até pausar coleta')),
                ('meses_garantia_padrao', models.PositiveIntegerField(default=12, help_text='Duração (em meses) da garantia criada automaticamente ao registrar uma nova usina. Só afeta garantias criadas a partir da próxima coleta.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Meses de garantia padrão')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configuração do Sistema',
            },
        ),
    ]
