# Generated by Django 5.1.15 on 2026-04-15 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleta', '0002_configuracaosistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='dias_aviso_garantia_proxima',
            field=models.PositiveIntegerField(default=30, help_text='Gera alerta nível "aviso" quando a garantia da usina estiver a este número de dias ou menos do fim.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Aviso prévio de garantia (dias)'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='dias_aviso_garantia_urgente',
            field=models.PositiveIntegerField(default=7, help_text='Escala o alerta para nível "importante" quando a garantia estiver a este número de dias ou menos do fim.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Aviso urgente de garantia (dias)'),
        ),
    ]
