# Generated by Django 5.1.15 on 2026-04-15 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleta', '0003_configuracaosistema_dias_aviso_garantia_proxima_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaosistema',
            name='dias_sem_comunicacao_pausar',
            field=models.PositiveIntegerField(default=60, help_text='Usinas sem snapshot há mais deste número de dias são automaticamente desativadas no início do próximo ciclo de coleta. Para retomar, acesse a página da usina e reative a coleta.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Dias sem comunicação até pausar coleta'),
        ),
    ]
