# Generated by Django 5.2.12 on 2026-03-22 02:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CredencialProvedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provedor', models.CharField(choices=[('solis', 'Solis Cloud'), ('hoymiles', 'Hoymiles S-Cloud'), ('fusionsolar', 'Huawei FusionSolar'), ('solarman', 'Solarman Pro')], max_length=30, unique=True)),
                ('credenciais_enc', models.TextField(help_text='Credenciais criptografadas com Fernet. Não editar manualmente.')),
                ('ativo', models.BooleanField(default=True)),
                ('precisa_atencao', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credencial de Provedor',
                'verbose_name_plural': 'Credenciais de Provedores',
            },
        ),
        migrations.CreateModel(
            name='CacheTokenProvedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados_token_enc', models.TextField()),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('credencial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cache_token', to='provedores.credencialprovedor')),
            ],
            options={
                'verbose_name': 'Cache de Token',
                'verbose_name_plural': 'Cache de Tokens',
            },
        ),
    ]
