# Generated by Django 5.2.12 on 2026-03-22 02:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inversor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_inversor_provedor', models.CharField(max_length=200)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inversor',
                'verbose_name_plural': 'Inversores',
            },
        ),
        migrations.CreateModel(
            name='SnapshotUsina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coletado_em', models.DateTimeField()),
                ('data_medicao', models.DateTimeField(blank=True, null=True)),
                ('potencia_kw', models.FloatField(default=0.0)),
                ('energia_hoje_kwh', models.FloatField(default=0.0)),
                ('energia_mes_kwh', models.FloatField(default=0.0)),
                ('energia_total_kwh', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('aviso', 'Aviso'), ('offline', 'Offline'), ('construcao', 'Em construção')], default='normal', max_length=15)),
                ('qtd_inversores', models.IntegerField(default=0)),
                ('qtd_inversores_online', models.IntegerField(default=0)),
                ('qtd_alertas', models.IntegerField(default=0)),
                ('payload_bruto', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Snapshot de Usina',
                'verbose_name_plural': 'Snapshots de Usinas',
                'ordering': ['-coletado_em'],
            },
        ),
        migrations.CreateModel(
            name='SnapshotInversor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coletado_em', models.DateTimeField()),
                ('data_medicao', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('normal', 'Normal'), ('aviso', 'Aviso'), ('offline', 'Offline')], default='normal', max_length=10)),
                ('pac_kw', models.FloatField(default=0.0)),
                ('energia_hoje_kwh', models.FloatField(default=0.0)),
                ('energia_total_kwh', models.FloatField(default=0.0)),
                ('soc_bateria', models.FloatField(blank=True, null=True)),
                ('strings_mppt', models.JSONField(default=dict)),
                ('payload_bruto', models.JSONField(default=dict)),
                ('inversor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='usinas.inversor')),
            ],
            options={
                'verbose_name': 'Snapshot de Inversor',
                'verbose_name_plural': 'Snapshots de Inversores',
                'ordering': ['-coletado_em'],
            },
        ),
        migrations.AddField(
            model_name='inversor',
            name='ultimo_snapshot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='usinas.snapshotinversor'),
        ),
        migrations.CreateModel(
            name='Usina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_usina_provedor', models.CharField(max_length=200)),
                ('provedor', models.CharField(max_length=30)),
                ('nome', models.CharField(max_length=200)),
                ('capacidade_kwp', models.FloatField(default=0.0)),
                ('fuso_horario', models.CharField(default='America/Sao_Paulo', max_length=50)),
                ('endereco', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('credencial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usinas', to='provedores.credencialprovedor')),
                ('ultimo_snapshot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='usinas.snapshotusina')),
            ],
            options={
                'verbose_name': 'Usina',
                'verbose_name_plural': 'Usinas',
            },
        ),
        migrations.AddField(
            model_name='snapshotusina',
            name='usina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='usinas.usina'),
        ),
        migrations.AddField(
            model_name='inversor',
            name='usina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inversores', to='usinas.usina'),
        ),
        migrations.AddIndex(
            model_name='snapshotinversor',
            index=models.Index(fields=['inversor', '-coletado_em'], name='usinas_snap_inverso_767fcb_idx'),
        ),
        migrations.AddIndex(
            model_name='usina',
            index=models.Index(fields=['provedor'], name='usinas_usin_provedo_1fa420_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usina',
            unique_together={('id_usina_provedor', 'provedor')},
        ),
        migrations.AddIndex(
            model_name='snapshotusina',
            index=models.Index(fields=['usina', '-coletado_em'], name='usinas_snap_usina_i_95c883_idx'),
        ),
        migrations.AddIndex(
            model_name='snapshotusina',
            index=models.Index(fields=['-coletado_em'], name='usinas_snap_coletad_d8080a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inversor',
            unique_together={('usina', 'id_inversor_provedor')},
        ),
    ]
