# Generated by Django 5.1.15 on 2026-04-08 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usinas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarantiaUsina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('meses', models.PositiveIntegerField()),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='garantia', to='usinas.usina')),
            ],
            options={
                'verbose_name': 'Garantia de Usina',
                'verbose_name_plural': 'Garantias de Usinas',
            },
        ),
    ]
