# Generated by Django 5.2.13 on 2026-04-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usinas', '0004_merge_garantiausina_snapshotinversor'),
    ]

    operations = [
        migrations.AddField(
            model_name='usina',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usina',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
