# Generated by Django 5.2.13 on 2026-04-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usinas', '0005_usina_add_lat_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='usina',
            name='cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usina',
            name='telefone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
