# Generated by Django 5.1.15 on 2026-04-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usinas', '0006_usina_add_cidade_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='usina',
            name='tensao_sobretensao_v',
            field=models.FloatField(default=240.0, help_text='Tensão AC a partir da qual gerar alerta de sobretensão. Padrão 240V — ajustar por região se necessário.', verbose_name='Limite de sobretensão AC (V)'),
        ),
    ]
