# Generated by Django 5.2.13 on 2026-04-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credencialprovedor',
            name='provedor',
            field=models.CharField(choices=[('solis', 'Solis Cloud'), ('hoymiles', 'Hoymiles S-Cloud'), ('fusionsolar', 'Huawei FusionSolar'), ('solarman', 'Solarman Pro'), ('auxsol', 'AuxSol Cloud')], max_length=30, unique=True),
        ),
    ]
