# Generated by Django 5.2.13 on 2026-04-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provedores', '0002_add_auxsol_provedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='credencialprovedor',
            name='intervalo_coleta_minutos',
            field=models.PositiveIntegerField(default=10, help_text='Intervalo entre coletas em minutos. Ex: 5, 10, 15, 30.'),
        ),
    ]
