# Generated by Django 5.2.13 on 2026-04-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provedores', '0003_add_intervalo_coleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credencialprovedor',
            name='intervalo_coleta_minutos',
            field=models.PositiveIntegerField(default=30, help_text='Intervalo entre coletas em minutos. Mínimo: 30 minutos.'),
        ),
    ]
