# Generated by Django 5.2.12 on 2026-03-22 02:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usinas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_alerta_provedor', models.CharField(blank=True, max_length=200)),
                ('equipamento_sn', models.CharField(blank=True, max_length=100, verbose_name='Serial do equipamento')),
                ('mensagem', models.TextField(verbose_name='Descrição do problema')),
                ('nivel', models.CharField(choices=[('critico', 'Crítico'), ('aviso', 'Aviso')], db_index=True, default='aviso', max_length=10)),
                ('inicio', models.DateTimeField(verbose_name='Início do problema')),
                ('fim', models.DateTimeField(blank=True, null=True, verbose_name='Fim do problema')),
                ('estado', models.CharField(choices=[('ativo', 'Ativo'), ('em_atendimento', 'Em atendimento'), ('resolvido', 'Resolvido')], db_index=True, default='ativo', max_length=15)),
                ('sugestao', models.TextField(blank=True, verbose_name='Sugestão de resolução')),
                ('anotacoes', models.TextField(blank=True, verbose_name='Anotações da equipe')),
                ('notificacao_enviada', models.BooleanField(default=False)),
                ('payload_bruto', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='usinas.usina')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-inicio'],
                'indexes': [models.Index(fields=['estado', '-inicio'], name='alertas_ale_estado_f68fda_idx'), models.Index(fields=['nivel', 'estado'], name='alertas_ale_nivel_8260b9_idx'), models.Index(fields=['usina', 'estado'], name='alertas_ale_usina_i_0402c4_idx')],
                'unique_together': {('usina', 'id_alerta_provedor')},
            },
        ),
    ]
