# Generated by Django 5.1.15 on 2026-04-15 18:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0002_add_notification_levels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('tipo', models.CharField(choices=[('alerta', 'Alerta'), ('sistema', 'Sistema'), ('garantia', 'Garantia'), ('outro', 'Outro')], db_index=True, default='sistema', max_length=20)),
                ('nivel', models.CharField(choices=[('info', 'Info'), ('aviso', 'Aviso'), ('importante', 'Importante'), ('critico', 'Crítico')], db_index=True, default='info', max_length=15)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('apenas_staff', models.BooleanField(db_index=True, default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['-criado_em'], name='notificacoe_criado__e02e00_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificacaoLeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lida_em', models.DateTimeField(auto_now_add=True)),
                ('notificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='notificacoes.notificacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_lidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leitura de Notificação',
                'verbose_name_plural': 'Leituras de Notificações',
                'indexes': [models.Index(fields=['usuario', 'notificacao'], name='notificacoe_usuario_dfb4df_idx')],
                'unique_together': {('usuario', 'notificacao')},
            },
        ),
    ]
