# Generated by Django 5.2.12 on 2026-03-22 02:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogColeta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('parcial', 'Parcial'), ('erro', 'Erro'), ('auth_erro', 'Erro de autenticação')], max_length=15)),
                ('usinas_coletadas', models.IntegerField(default=0)),
                ('inversores_coletados', models.IntegerField(default=0)),
                ('alertas_sincronizados', models.IntegerField(default=0)),
                ('detalhe_erro', models.TextField(blank=True)),
                ('duracao_ms', models.IntegerField(default=0)),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('credencial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_coleta', to='provedores.credencialprovedor')),
            ],
            options={
                'verbose_name': 'Log de Coleta',
                'verbose_name_plural': 'Logs de Coleta',
                'ordering': ['-iniciado_em'],
                'indexes': [models.Index(fields=['credencial', '-iniciado_em'], name='coleta_logc_credenc_2d70b0_idx')],
            },
        ),
    ]
