# Generated by Django 5.2.12 on 2026-03-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp')], max_length=20, unique=True)),
                ('ativo', models.BooleanField(default=False)),
                ('destinatarios', models.TextField(blank=True, help_text='Um por linha ou separados por vírgula. Email: endereços. WhatsApp: +55DDNNNNNNNNN')),
                ('notificar_critico', models.BooleanField(default=True, verbose_name='Notificar alertas críticos')),
                ('notificar_aviso', models.BooleanField(default=False, verbose_name='Notificar alertas de aviso')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Notificação',
                'verbose_name_plural': 'Configurações de Notificação',
            },
        ),
    ]
