# Generated by Django 5.2.13 on 2026-04-11 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0003_fusionsolar_catalog'),
        ('usinas', '0006_usina_add_cidade_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='categoria',
            field=models.CharField(blank=True, choices=[('tensao_zero', 'Tensão zero — usina desligada'), ('sobretensao', 'Sobretensão — tensão AC ≥ 240V'), ('corrente_baixa', 'Corrente baixa prolongada — possível problema'), ('sem_geracao_diurna', 'Sem geração em horário comercial (8h-18h)'), ('sem_comunicacao', 'Sem comunicação — possível falha de Wi-Fi'), ('geracao_abaixo', 'Geração abaixo do previsto'), ('geracao_acima', 'Geração acima do previsto'), ('temperatura_alta', 'Temperatura elevada do inversor'), ('outro', 'Outro')], db_index=True, help_text='Preenchido automaticamente para alertas internos.', max_length=30, verbose_name='Categoria (alertas internos)'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='origem',
            field=models.CharField(choices=[('provedor', 'Provedor'), ('interno', 'Interno')], db_index=True, default='provedor', max_length=10, verbose_name='Origem do alerta'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='estado',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('resolvido', 'Resolvido')], db_index=True, default='ativo', max_length=15),
        ),
        migrations.AlterField(
            model_name='catalogoalarme',
            name='tipo',
            field=models.CharField(blank=True, choices=[('equipamento', 'Equipamento — falha em hardware (inversor, string, módulo)'), ('comunicacao', 'Comunicação — perda de link / conectividade'), ('rede_eletrica', 'Rede elétrica — instabilidade na rede (grid)'), ('sistema_desligado', 'Sistema desligado — usina completamente parada'), ('preventivo', 'Preventivo — informativo, manutenção, sem urgência')], help_text='Preenchida automaticamente na primeira detecção. Pode ser corrigida manualmente.', max_length=100, verbose_name='Categoria'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['origem', 'estado'], name='alertas_ale_origem_c3dea2_idx'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['categoria', 'estado'], name='alertas_ale_categor_50b9ed_idx'),
        ),
    ]
