# Generated by Django 5.2.13 on 2026-04-11 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0004_add_origem_categoria_alertas'),
        ('usinas', '0006_usina_add_cidade_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupressaoInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=30, verbose_name='Categoria suprimida')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo da supressão')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supressoes_internas', to='usinas.usina')),
            ],
            options={
                'verbose_name': 'Supressão de Alerta Interno',
                'verbose_name_plural': 'Supressões de Alertas Internos',
                'unique_together': {('usina', 'categoria')},
            },
        ),
    ]
