# Generated by Django 5.1.15 on 2026-04-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0005_add_supressao_interna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='categoria',
            field=models.CharField(blank=True, choices=[('tensao_zero', 'Tensão zero — usina desligada'), ('sobretensao', 'Sobretensão — tensão AC ≥ 240V'), ('corrente_baixa', 'Corrente baixa prolongada — possível problema'), ('sem_geracao_diurna', 'Sem geração em horário comercial (8h-18h)'), ('sem_comunicacao', 'Sem comunicação — possível falha de Wi-Fi'), ('geracao_abaixo', 'Geração abaixo do previsto'), ('geracao_acima', 'Geração acima do previsto'), ('temperatura_alta', 'Temperatura elevada do inversor'), ('garantia_expirando', 'Garantia próxima do fim'), ('outro', 'Outro')], db_index=True, help_text='Preenchido automaticamente para alertas internos.', max_length=30, verbose_name='Categoria (alertas internos)'),
        ),
    ]
