# Generated by Django 5.2.13 on 2026-04-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0006_alter_alerta_categoria'),
        ('usinas', '0007_usina_tensao_sobretensao_v'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='alerta',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ativo'), ('origem', 'interno')), fields=('usina', 'categoria'), name='uniq_alerta_ativo_interno_por_usina_categoria'),
        ),
        migrations.AddConstraint(
            model_name='alerta',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ativo'), ('origem', 'provedor')), fields=('usina', 'catalogo_alarme'), name='uniq_alerta_ativo_provedor_por_usina_catalogo'),
        ),
    ]
